In [1]:
import numpy as np

# 1
(B) Create a 1D NumPy array of integers from 10 to 20 inclusive.

In [6]:
x = np.arange(10, 21)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 2
Generate a 3x3 array filled with zeros.

In [10]:
arr = np.zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 3
Create a 2x4 array of ones with data type int32.

In [17]:
arr = np.zeros((2, 4), dtype=np.int32)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

# 4
Use np.arange to create an array of even numbers from 2 to 10.

In [21]:
arr = np.arange(2, 11, 2)
arr

array([ 2,  4,  6,  8, 10])

# 5
Create a 4x4 array with values from 1 to 16 using np.arange and reshape.

In [23]:
arr = np.arange(1, 17)
reshaped = np.reshape(arr, (4, 4))
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# 6
Generate a 1D array of 10 evenly spaced values between 0 and 5 using np.linspace.

In [24]:
arr = np.linspace(0, 5, num=10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# 7
Create a 5x5 identity matrix using np.eye.

In [25]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 8
Generate a 3x3 array of random integers between 1 and 100 using np.random.randint.

In [39]:
arr = np.random.randint(1, 100, size=(3, 3))
arr

array([[88, 92, 81],
       [66, 95, 83],
       [26, 26, 54]], dtype=int32)

# 9
Create a 2x3x2 array filled with the value 7 using np.full.

In [40]:
arr = np.full([2, 3, 2], 7, dtype=int)
arr

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

# 10
Use np.logspace to create a 1D array of 5 logarithmically spaced values between 10^1 and 10^5.

In [43]:
arr = np.logspace(1, 5, num=5)
arr

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

# 11
Reshape a 1D array of 12 elements into a 3x4 array.

In [45]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 12
Flatten a 2x3 array into a 1D array using ravel.

In [55]:
arr = np.random.randint(10, size=(2, 3))

In [54]:
flattened = arr.reshape(-1)
flattened

array([2, 2, 5, 3, 2, 9], dtype=int32)

# 13
Extract the second row of a 4x4 array with values from 1 to 16.

In [58]:
arr = np.random.randint(30, size=(4, 4))
arr

array([[13, 11, 29,  1],
       [13, 23, 12,  9],
       [ 5,  1, 19, 12],
       [25, 19, 29, 29]], dtype=int32)

In [62]:
second_row = arr[1]
filtered_values = second_row[(second_row > 1) & (second_row < 16)]
filtered_values

array([13, 12,  9], dtype=int32)

# 14
Swap the first and last rows of a 3x3 array.

In [63]:
arr = np.random.randint(10, size=(3, 3))
arr

array([[5, 4, 8],
       [9, 4, 0],
       [6, 8, 3]], dtype=int32)

In [64]:
arr[[0, 2]] = arr[[2, 0]]
arr

array([[6, 8, 3],
       [9, 4, 0],
       [5, 4, 8]], dtype=int32)

# 15
Replace all elements greater than 5 in a 1D array with 0.

In [66]:
arr = np.random.randint(10, size=(10))
arr

array([2, 7, 5, 6, 7, 4, 3, 9, 6, 3], dtype=int32)

In [68]:
arr[arr > 5] = 0
arr

array([2, 0, 5, 0, 0, 4, 3, 0, 0, 3], dtype=int32)

# 16
Create a 5x5 array of ones and set the border elements to 0.

In [70]:
arr = np.zeros((5, 5))
arr[1:-1, 1:-1] = 1
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# 17
Extract the diagonal elements of a 4x4 array.

In [72]:
arr = np.random.randint(4, size=(4, 4))
arr

array([[1, 2, 0, 1],
       [1, 1, 3, 3],
       [3, 2, 1, 0],
       [2, 1, 2, 3]], dtype=int32)

In [73]:
diagonal_array = np.diagonal(arr)
diagonal_array

array([1, 1, 1, 3], dtype=int32)

# 18
Reverse the order of columns in a 3x4 array.

In [74]:
arr = np.random.randint(10, size=(3, 4))
arr

array([[8, 4, 6, 1],
       [0, 8, 9, 2],
       [1, 0, 2, 8]], dtype=int32)

In [75]:
reversed_column = np.fliplr(arr)
reversed_column

array([[1, 6, 4, 8],
       [2, 9, 8, 0],
       [8, 2, 0, 1]], dtype=int32)

# 19
Create a 3x3 array and stack it vertically with its transpose.

In [76]:
arr = np.random.randint(10, size=(3, 3))
arr

array([[3, 2, 8],
       [8, 1, 0],
       [2, 2, 9]], dtype=int32)

In [79]:
transpose = arr.T
result = np.vstack((arr, transpose))
result

array([[3, 2, 8],
       [8, 1, 0],
       [2, 2, 9],
       [3, 8, 2],
       [2, 1, 2],
       [8, 0, 9]], dtype=int32)

# 20
Split a 6x6 array into three 2x6 subarrays horizontally.

In [80]:
arr = np.random.randint(10, size=(6, 6))
arr

array([[8, 3, 0, 8, 6, 0],
       [9, 1, 1, 2, 8, 4],
       [3, 2, 9, 9, 1, 3],
       [3, 9, 9, 6, 9, 7],
       [8, 7, 7, 3, 0, 6],
       [9, 0, 1, 3, 0, 6]], dtype=int32)

In [83]:
splitted_array = np.array_split(arr, 3) # or I can use vsplit function
splitted_array

[array([[8, 3, 0, 8, 6, 0],
        [9, 1, 1, 2, 8, 4]], dtype=int32),
 array([[3, 2, 9, 9, 1, 3],
        [3, 9, 9, 6, 9, 7]], dtype=int32),
 array([[8, 7, 7, 3, 0, 6],
        [9, 0, 1, 3, 0, 6]], dtype=int32)]

# 21
Add two 1D arrays of length 5 element-wise.

In [84]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.add(a, b)

array([5, 7, 9])

# 22
Multiply a 2x3 array by a scalar value of 4.

In [95]:
arr = np.random.randint(10, size=(2, 3))
arr

array([[5, 1, 3],
       [2, 7, 7]], dtype=int32)

In [96]:
row = len(arr)
column = len(arr[0])
magic_number = 4

for i in range(row):
    for j in range(column):
        arr[i][j] *= magic_number
arr

array([[20,  4, 12],
       [ 8, 28, 28]], dtype=int32)

# 23
Compute the element-wise square of a 1D array [1, 2, 3, 4].

In [100]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [104]:
result = arr ** 2
result

array([ 1,  4,  9, 16])

# 24
Perform element-wise division of two 2x2 arrays.

In [129]:
a = np.array(([10, 6], [24, 21]))
b = np.array(([5, 8], [6, 7]))
print('A:\n', a)
print('B:\n', b)

A:
 [[10  6]
 [24 21]]
B:
 [[5 8]
 [6 7]]


In [132]:
result = a / b
result

array([[2.  , 0.75],
       [4.  , 3.  ]])

# 25
Apply np.sin to a 1D array of 5 evenly spaced angles between 0 and π.

In [3]:
angles = np.linspace(0, np.pi, 5)
sin_values = np.sin(angles)
sin_values

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

# 26
Add a 1D array of shape (3,) to a 2D array of shape (2, 3) using broadcasting.

In [5]:
one_d_array = np.array([1, 2, 3])
two_d_array = np.array([[4, 5, 6], [7, 8, 9]])

In [6]:
result = one_d_array + two_d_array
result

array([[ 5,  7,  9],
       [ 8, 10, 12]])

# 27
Compute the element-wise product of two 3x3 arrays with random integers between 1 and 10.

In [11]:
arr1 = np.random.randint(1, 11, size=(3, 3))
arr2 = np.random.randint(1, 11, size=(3, 3))
print('A:\n', arr1)
print('B:\n', arr2)

A:
 [[10  4  3]
 [ 5 10  7]
 [ 2  9  9]]
B:
 [[8 5 2]
 [9 5 6]
 [9 8 2]]


In [12]:
result = arr1 * arr2
result

array([[80, 20,  6],
       [45, 50, 42],
       [18, 72, 18]], dtype=int32)

# 28
Raise all elements of a 2x2 array to the power of 3.

In [13]:
arr = np.random.randint(10, size=(2, 2))
arr

array([[8, 2],
       [2, 8]], dtype=int32)

In [14]:
result = arr ** 3
result

array([[512,   8],
       [  8, 512]], dtype=int32)

# 29
Create a 4x4 array and subtract its row-wise mean from each element.

In [16]:
arr = np.random.randint(10, size=(4, 4))
arr

array([[5, 4, 8, 3],
       [9, 1, 0, 1],
       [1, 6, 3, 7],
       [7, 9, 0, 6]], dtype=int32)

In [33]:
row_mean = arr.mean(axis=1, keepdims=True)
normalized = arr - row_mean
normalized

array([[ 0.  , -1.  ,  3.  , -2.  ],
       [ 6.25, -1.75, -2.75, -1.75],
       [-3.25,  1.75, -1.25,  2.75],
       [ 1.5 ,  3.5 , -5.5 ,  0.5 ]])

# 30
Use broadcasting to multiply a 3x1 array with a 1x3 array to get a 3x3 result.

In [6]:
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])

In [8]:
result = a * b

In [9]:
result

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

# 31
Compute the mean of a 1D array of 10 random integers.

In [19]:
arr = np.random.randint(10, size=(10))
arr

array([3, 1, 1, 0, 4, 7, 6, 2, 8, 4], dtype=int32)

In [21]:
mean = np.mean(arr)
mean

np.float64(3.6)

# 32
Find the maximum value in a 3x3 array.

In [22]:
arr = np.random.randint(10, size=(3, 3))
arr

array([[2, 3, 8],
       [3, 6, 9],
       [2, 9, 7]], dtype=int32)

In [23]:
maximum = np.max(arr)
maximum

np.int32(9)

# 33
Calculate the sum of all elements in a 2x4 array.

In [25]:
arr = np.random.randint(10, size=(2, 4))
arr

array([[3, 4, 3, 4],
       [5, 3, 1, 7]], dtype=int32)

In [26]:
sum_arr = np.sum(arr)
sum_arr

np.int64(30)

# 34
Compute the standard deviation of a 1D array with values from 1 to 10.

In [29]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
std = np.std(arr)
std

np.float64(2.8722813232690143)

# 35
Find the row-wise minimum of a 4x4 array.

In [31]:
arr = np.random.randint(10, size=(4, 4))
arr

array([[3, 2, 7, 5],
       [8, 9, 8, 7],
       [8, 5, 4, 4],
       [0, 1, 0, 5]], dtype=int32)

In [33]:
min_row = arr.min(axis=1, keepdims=True)
min_row

array([[2],
       [7],
       [4],
       [0]], dtype=int32)

# 36
Calculate the median of a 1D array containing [1, 2, 3, 4, 5].

In [34]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [36]:
median = np.median(arr)
median

np.float64(3.0)

# 37
Compute the column-wise mean of a 5x5 array of random floats between 0 and 1.

In [43]:
arr = np.random.rand(5, 5)
arr

array([[0.49055892, 0.2858216 , 0.88099673, 0.89514037, 0.22956369],
       [0.06906509, 0.27453145, 0.14380866, 0.15976841, 0.26772923],
       [0.03684755, 0.4490184 , 0.54313409, 0.07973669, 0.43192856],
       [0.65612997, 0.09791033, 0.6478203 , 0.13360937, 0.97275218],
       [0.92710414, 0.4077793 , 0.89519979, 0.24589152, 0.12459979]])

In [45]:
mean = (arr.mean(axis=1, keepdims=True)).round(2)
mean

array([[0.56],
       [0.18],
       [0.31],
       [0.5 ],
       [0.52]])

# 38
Replace all np.nan values in a 1D array with the array’s mean (excluding np.nan).

In [54]:
arr = np.array([1, 2, 3, np.nan, 5, np.nan, np.nan, 8, np.nan, 10])
arr

array([ 1.,  2.,  3., nan,  5., nan, nan,  8., nan, 10.])

In [63]:
mean = np.nanmean(arr)

arr[np.isnan(arr)] = mean
arr

array([ 1.        ,  2.        ,  3.        ,  4.83333333,  5.        ,
        4.83333333,  4.83333333,  8.        ,  4.83333333, 10.        ])

# 39
Find the index of the maximum value in a 2D array using np.argmax.

In [77]:
arr = np.random.randint(10, size=(2, 2))
arr

array([[4, 7],
       [8, 3]], dtype=int32)

In [82]:
max_index = np.argmax(arr)
max_index_2d = np.unravel_index(max_index, arr.shape)
max_index_2d

(np.int64(1), np.int64(0))

# 40
Compute the cumulative sum of a 1D array of 6 elements.

In [83]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [85]:
cumulative_sum = np.cumsum(arr)
cumulative_sum

array([ 1,  3,  6, 10, 15, 21])

# 41
Compute the dot product of two 1D arrays of length 3.

In [87]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [92]:
dot_product = np.dot(a, b)
dot_product

np.int64(32)

# 42
Find the transpose of a 2x3 array.

In [93]:
arr = np.random.randint(10, size=(2, 3))
arr

array([[1, 4, 8],
       [7, 6, 4]], dtype=int32)

In [94]:
transpose = arr.T
transpose

array([[1, 7],
       [4, 6],
       [8, 4]], dtype=int32)

# 43
Perform matrix multiplication of two 2x2 arrays using np.matmul.

In [99]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [101]:
matrix_multiplication = np.matmul(a, b)
matrix_multiplication

array([[19, 22],
       [43, 50]])

# 44
Calculate the determinant of a 2x2 array using np.linalg.det.

In [107]:
arr = np.random.randint(10, size=(2, 2))
arr

array([[3, 0],
       [7, 4]], dtype=int32)

In [109]:
determinant = (np.linalg.det(arr)).round(0)
determinant

np.float64(12.0)

# 45
Compute the trace (sum of diagonal elements) of a 3x3 array.

In [113]:
arr = np.random.randint(10, size=(3, 3))
arr

array([[2, 9, 2],
       [2, 7, 9],
       [6, 9, 6]], dtype=int32)

In [114]:
matrix_trace = arr.trace()
matrix_trace

np.int64(15)

# 46
Find the inverse of a 2x2 array using np.linalg.inv.

In [122]:
arr = np.random.randint(10, size=(2, 2))
arr

array([[0, 9],
       [2, 8]], dtype=int32)

In [123]:
inverse_matrix = np.linalg.inv(arr)
inverse_matrix

array([[-0.44444444,  0.5       ],
       [ 0.11111111,  0.        ]])

# 47
Solve a system of linear equations with a 3x3 coefficient matrix and a 3x1 vector
using np.linalg.solve.

In [124]:
arr1 = np.random.randint(10, size=(3, 3))
arr1

array([[9, 6, 4],
       [1, 7, 9],
       [3, 6, 2]], dtype=int32)

In [125]:
arr2 = np.random.randint(10, size=(3))
arr2

array([8, 7, 2], dtype=int32)

In [126]:
solved = np.linalg.solve(arr1, arr2)
solved

array([ 0.68148148, -0.32592593,  0.95555556])

# 48
Compute the eigenvalues of a 2x2 array using np.linalg.eigvals.

In [130]:
arr = np.random.randint(10, size=(2, 2))
arr

array([[8, 5],
       [3, 9]], dtype=int32)

In [131]:
eigenvalue = np.linalg.eigvals(arr)

In [132]:
eigenvalue

array([ 4.59487516, 12.40512484])

# 49
Perform matrix multiplication of a 3x2 and a 2x3 array to get a 3x3 result.

In [134]:
arr1 = np.random.randint(10, size=(3, 2))
arr1

array([[5, 4],
       [7, 7],
       [9, 8]], dtype=int32)

In [135]:
arr2 = np.random.randint(10, size=(2, 3))
arr2

array([[1, 1, 9],
       [2, 8, 3]], dtype=int32)

In [137]:
result = np.dot(arr1, arr2)
result

array([[ 13,  37,  57],
       [ 21,  63,  84],
       [ 25,  73, 105]], dtype=int32)

# 50
Normalize a 1D array by dividing it by its Euclidean norm (use np.linalg.norm).

In [138]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [140]:
normalized = np.linalg.norm(arr)
normalized_arr = arr / normalized
normalized_arr

array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])